package com.lambda.Model;


import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.List;

@DynamoDBTable(tableName = "cc_tests")
@DynamoDBDocument
public class CandidateTest {


    private String testUUID;
    private String username;
    private List<String> answers;
    private Double score;
    private Test test;
    private String candidateUUID;
    private String recruiter;
    private String requestToken;



    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getTestUUID() {
        return testUUID;
    }
    public void setTestUUID(String testUUID) {
        this.testUUID = testUUID;
    }

    @DynamoDBAttribute(attributeName = "username")
    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @DynamoDBAttribute(attributeName = "TestTest")
    public Test getTest() {
        return test;
    }

    public void setTest(Test test) {
        this.test = test;
    }
    @DynamoDBAttribute(attributeName = "answers")
    public List<String> getAnswers() {
        return answers;
    }

    public void setAnswers(List<String> answers) {
        this.answers = answers;
    }

    @DynamoDBAttribute(attributeName = "score")
    public Double getScore() {
        return score;
    }

    public void setScore(Double score) {
        this.score = score;
    }

    @DynamoDBAttribute(attributeName = "rec")
    public String getRecruiter() {
        return recruiter;
    }

    public void setRecruiter(String recruiter) {
        this.recruiter = recruiter;
    }

    @DynamoDBAttribute(attributeName = "candidateUUID")
    public String getCandidateUUID() {
        return candidateUUID;
    }

    public void setCandidateUUID(String candidateUUID) {
        this.candidateUUID = candidateUUID;
    }

    @DynamoDBIgnore
    public String getRequestToken() {
        return requestToken;
    }

    public void setRequestToken(String requestToken) {
        this.requestToken = requestToken;
    }
}
